dagen = ("maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag", "zondag")
print("Alle dagen van de week zijn: " + dagen[0] + ", " + dagen[1] + ", " + dagen[2] + ", " + dagen[3] + ", " + dagen[4] + ", " + dagen[5] + ", " + dagen[6])
print("De werkdagen zijn: " + dagen[0] + ", " + dagen[1] + ", " + dagen[2] + ", " + dagen[3] + ", " + dagen[4])
print("De weekenddagen zijn: " + dagen[5] + ", " + dagen[6])
print("Alle dagen van de week in omgekeerde volgorde zijn: " + dagen[6] + ", " + dagen[5] + ", " + dagen[4] + ", " + dagen[3] + ", " + dagen[2] + ", " + dagen[1] + ", " + dagen[0])
print("De werkdagen in omgekeerde volgorde zijn: " + dagen[4] + ", " + dagen[3] + ", " + dagen[2] + ", " + dagen[1] + ", " + dagen[0])
print("De weekenddagen in omgekeerde volgorde zijn: " + dagen[6] + ", " + dagen[5])
print(dagen[2:4])
print(dagen[6::-1])
print(dagen[:7:1])
print(dagen[7:4:-1])