# EERST FUNCTIES, DAN

# VARIABELEN EN CONSTANTEN
OLIEBOL_PRIJS = 99
PRIJS_10_OLIEBOLLEN = 750
APPEPFLAP_PRIJS = 149

AANTAL_OLIEBOLLEN = 11
AANTAL_APPLEFLAPPEN = 0

# BEREKENINGEN
prijs_totaal = AANTAL_OLIEBOLLEN * OLIEBOL_PRIJS + AANTAL_APPLEFLAPPEN * APPEPFLAP_PRIJS
totaal_eur = prijs_totaal / 100   

print(f"De {AANTAL_OLIEBOLLEN} oliebollen en {AANTAL_APPLEFLAPPEN} appelflappen kosten samen: {totaal_eur}")