naam = input("wat is je naam?")
adres = input("wat is je adres?")
postcode = input("wat is je postcode?")
woonplaats = input("wat is je woonplaats?")
print("----------------------------------------------------")
print("|  Naam      : " + naam)
print("|  Adres     : " + adres)
print("|  Postcode  : " + postcode)
print("|  Woonplaats: " + woonplaats)
print("----------------------------------------------------")
# deze code werkt 